In [1]:
import pandas as pd
import numpy as np

In [3]:
data=[1,2,3,4]
series1=pd.Series(data)
series1

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
series1=pd.Series(data, index=['a','b','c','d'])
series1

a    1
b    2
c    3
d    4
dtype: int64

dictionary={'fruits':['apples','banana','oranges'], 'count':[12,20,30]}
df=pd.DataFrame(dictionary)
df


In [6]:
series=pd.Series([6,12], index=['a','b'])
df=pd.DataFrame(series)
df

0
a   6
b  12

In [8]:
numpyarray=np.array([[50000,60000,80000,55000],['John','James','peter','jordan']])
df=pd.DataFrame({'name': numpyarray[1],'salary':numpyarray[0]})
df

name salary
0    John  50000
1   James  60000
2   peter  80000
3  jordan  55000

In [10]:
df('Salary').max()

TypeError: 'DataFrame' object is not callable

In [11]:
player=['player1','player2','player3']
score=[8,9,6]
title=['Game1','Game2','Game3']
df1=pd.DataFrame({'player':player, 'score':score, 'title':title})
df1


player  score  title
0  player1      8  Game1
1  player2      9  Game2
2  player3      6  Game3

In [12]:
player=['player1','player5','player6']
power=['punch','kick','elbow']
title=['Game1','Game5','Game6']
df2=pd.DataFrame({'player':player, 'power':power, 'title':title})
df2

player  power  title
0  player1  punch  Game1
1  player5   kick  Game5
2  player6  elbow  Game6

In [13]:
df1.merge(df2, on='title', how='inner')

player_x  score  title player_y  power
0  player1      8  Game1  player1  punch

In [14]:
df1.merge(df2)

player  score  title  power
0  player1      8  Game1  punch

In [15]:
df1.merge(df2, on='player', how='left')

player  score title_x  power title_y
0  player1      8   Game1  punch   Game1
1  player2      9   Game2    NaN     NaN
2  player3      6   Game3    NaN     NaN

In [16]:
df1.merge(df2, on='player', how='right')

player  score title_x  power title_y
0  player1    8.0   Game1  punch   Game1
1  player5    NaN     NaN   kick   Game5
2  player6    NaN     NaN  elbow   Game6

In [17]:
df1.merge(df2, on='player', how='outer')

player  score title_x  power title_y
0  player1    8.0   Game1  punch   Game1
1  player2    9.0   Game2    NaN     NaN
2  player3    6.0   Game3    NaN     NaN
3  player5    NaN     NaN   kick   Game5
4  player6    NaN     NaN  elbow   Game6

In [23]:
player=['player1','player2','player3']
score=[8,9,6]
title=['Game1','Game2','Game3']
df3=pd.DataFrame({'player':player, 'score':score, 'title':title}, index={'L1','L2','L3'})
df3


player  score  title
L3  player1      8  Game1
L1  player2      9  Game2
L2  player3      6  Game3

In [25]:
player=['player1','player5','player6']
power=['punch','kick','elbow']
title=['Game1','Game5','Game6']
df4=pd.DataFrame({'players':player, 'power':power, 'titles':title}, index={'L2','L3','L4'})
df4

players  power titles
L4  player1  punch  Game1
L3  player5   kick  Game5
L2  player6  elbow  Game6

In [26]:
df3.join(df4, how='inner')

player  score  title  players  power titles
L3  player1      8  Game1  player5   kick  Game5
L2  player3      6  Game3  player6  elbow  Game6

In [27]:
df3.join(df4, how='left')

player  score  title  players  power titles
L3  player1      8  Game1  player5   kick  Game5
L1  player2      9  Game2      NaN    NaN    NaN
L2  player3      6  Game3  player6  elbow  Game6

In [28]:
pd.concat([df3,df4])

player  score  title  players  power titles
L3  player1    8.0  Game1      NaN    NaN    NaN
L1  player2    9.0  Game2      NaN    NaN    NaN
L2  player3    6.0  Game3      NaN    NaN    NaN
L4      NaN    NaN    NaN  player1  punch  Game1
L3      NaN    NaN    NaN  player5   kick  Game5
L2      NaN    NaN    NaN  player6  elbow  Game6

In [2]:
import numpy as np
a=np.array([10,20,30])
b=np.array([3,5,7])
a
b


array([3, 5, 7])

In [3]:
a

array([10, 20, 30])

In [4]:
np.mod(a,b)

array([1, 0, 2], dtype=int32)

In [5]:
np.remainder(a,b)

array([1, 0, 2], dtype=int32)

In [7]:
aa=np.array([[3,7],[9,11]])
aa

array([[ 3,  7],
       [ 9, 11]])

In [8]:
np.sort(aa)

array([[ 3,  7],
       [ 9, 11]])

In [9]:
np.sort(aa, axis=0)

array([[ 3,  7],
       [ 9, 11]])

In [10]:
ab=np.array([[30,40,0],[0,20,10],[50,0,60]])
ab


array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [11]:
np.nonzero(ab)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 1, 2, 0, 2], dtype=int64))

In [12]:
ac=np.arange(9.).reshape(3,3)
ac

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [13]:
ad=np.where(ac>3)
ad

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [15]:
aab=np.mod(ac,2)==0
aab

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [17]:
aac=np.extract(aab,ac)
aac

array([0., 2., 4., 6., 8.])

In [18]:
v1=np.array([3,2])
v2=np.array([1,4])
v3=np.add(v1,v2)
v3

array([4, 6])

In [19]:
v4=np.array([1,-2,5])
v5=np.array([4,3,1])
v6=np.multiply(v4,v5)
v6

array([ 4, -6,  5])

In [23]:
aa=np.arange(40)
aa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [26]:
aa.shape=(5,8)
aa

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [29]:
a=np.array([[1,0,0],[0,2,2],[3,0,0]])
a

array([[1, 0, 0],
       [0, 2, 2],
       [3, 0, 0]])

In [30]:
b=np.nonzero(a)
b

(array([0, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [32]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
b=a.T
b

array([[1, 3, 5],
       [2, 4, 6]])

In [34]:
a=([2,1,3])
b=([5,-2,0])
c=np.add(a,b)
c

array([ 7, -1,  3])